version: "3.9"  # optional since v1.27.0
services:
  node-red:
    image: dev:node-red-build
    restart: always
    network_mode: "host"
    ports:
      - "1880:1880"
  dataloader:
    image: dev:dataloader-build
    restart: always
    runtime: nvidia
    network_mode: "host"
    devices:
    - "/dev/video0:/dev/video0"
    ports:
      - "5550:5550"
  detection:
    image: dev:detection-build
    restart: always
    runtime: nvidia
    network_mode: "host"
    ports:
      - "5560:5560"
    